name: Build and Deploy
on:
  push:
    branches:
      - hubs.aelatgt.net.02.22
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build (App)
        run: |
          yarn
          yarn build

      - name: Install and Build (Hubs)
        working-directory: ./src/packages/excalidraw
        run: |
          yarn
          yarn build:hubs

      - name: Copy Hubs Build Artifacts
        run: |
          cp -r src/packages/excalidraw/dist/. build/static/js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
